import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 36,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#101010",
  },
  h1: { fontSize: 18, fontWeight: 700, marginBottom: 4 },
  h2: { fontSize: 13, fontWeight: 700, marginTop: 14, marginBottom: 4 },
  meta: { fontSize: 9, color: "#666", marginBottom: 16 },
  bullet: { marginLeft: 10, lineHeight: 1.3 },
});

export interface CarePlanPdfProps {
  patientName: string;
  gpName: string;
  reviewDue: string;
  problems: string[];
  goals: string[];
  team: string[];
}

export function CarePlanPdf(props: CarePlanPdfProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.h1}>Care plan — {props.patientName}</Text>
        <Text style={styles.meta}>
          Drafted by {props.gpName}. Review due {props.reviewDue}.
        </Text>

        <Text style={styles.h2}>Problems</Text>
        <View>
          {props.problems.map((p, i) => (
            <Text key={i} style={styles.bullet}>
              • {p}
            </Text>
          ))}
        </View>

        <Text style={styles.h2}>Goals</Text>
        <View>
          {props.goals.map((g, i) => (
            <Text key={i} style={styles.bullet}>
              • {g}
            </Text>
          ))}
        </View>

        <Text style={styles.h2}>Care team</Text>
        <View>
          {props.team.map((t, i) => (
            <Text key={i} style={styles.bullet}>
              • {t}
            </Text>
          ))}
        </View>

        <Text style={styles.meta}>Generated by Measured Metabolics.</Text>
      </Page>
    </Document>
  );
}
