import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 36,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#101010",
  },
  h1: { fontSize: 18, fontWeight: 700, marginBottom: 4 },
  h2: { fontSize: 13, fontWeight: 700, marginTop: 14, marginBottom: 4 },
  meta: { fontSize: 9, color: "#666", marginBottom: 16 },
  para: { lineHeight: 1.4 },
  rec: { marginTop: 6, paddingLeft: 10 },
  recTitle: { fontWeight: 700 },
});

export interface DietitianReportPdfProps {
  patientName: string;
  dietitianName: string;
  periodStart: string;
  periodEnd: string;
  summary: string;
  recommendations: Array<{ title: string; detail: string }>;
}

export function DietitianReportPdf(props: DietitianReportPdfProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.h1}>Dietitian Report — {props.patientName}</Text>
        <Text style={styles.meta}>
          Period {props.periodStart} – {props.periodEnd}. Drafted by{" "}
          {props.dietitianName}.
        </Text>

        <Text style={styles.h2}>30-second summary</Text>
        <View>
          <Text style={styles.para}>{props.summary}</Text>
        </View>

        <Text style={styles.h2}>Top recommendations</Text>
        {props.recommendations.map((r, i) => (
          <View key={i} style={styles.rec}>
            <Text style={styles.recTitle}>
              {i + 1}. {r.title}
            </Text>
            <Text style={styles.para}>{r.detail}</Text>
          </View>
        ))}

        <Text style={styles.meta}>
          Generated by CLOVE. AI-assisted draft, dietitian-approved before send.
        </Text>
      </Page>
    </Document>
  );
}
